# Generated by Django 5.2.10 on 2026-01-27 15:37

import django.db.models.deletion
from django.db import migrations, models

import i18n_fields.fields.boolean_field
import i18n_fields.fields.char_field
import i18n_fields.fields.float_field
import i18n_fields.fields.integer_field
import i18n_fields.fields.text_field
import i18n_fields.fields.uniqueslug_field
import i18n_fields.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    i18n_fields.fields.char_field.LocalizedCharField(
                        max_length=100, required=["en"]
                    ),
                ),
                (
                    "description",
                    i18n_fields.fields.text_field.LocalizedTextField(blank=True),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    i18n_fields.fields.char_field.LocalizedCharField(
                        max_length=200, required=["en"]
                    ),
                ),
                (
                    "slug",
                    i18n_fields.fields.uniqueslug_field.LocalizedUniqueSlugField(
                        include_time=False, populate_from="title", required=["en"]
                    ),
                ),
                (
                    "summary",
                    i18n_fields.fields.char_field.LocalizedCharField(
                        blank=True, max_length=500
                    ),
                ),
                (
                    "content",
                    i18n_fields.fields.text_field.LocalizedTextField(blank=True),
                ),
                (
                    "view_count",
                    i18n_fields.fields.integer_field.LocalizedIntegerField(blank=True),
                ),
                (
                    "rating",
                    i18n_fields.fields.float_field.LocalizedFloatField(blank=True),
                ),
                (
                    "is_featured",
                    i18n_fields.fields.boolean_field.LocalizedBooleanField(blank=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="articles.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-created_at"],
            },
            bases=(i18n_fields.mixins.AtomicSlugRetryMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    i18n_fields.fields.char_field.LocalizedCharField(
                        max_length=50, required=["en"]
                    ),
                ),
                (
                    "articles",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="articles.article"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
