# Generated by Django 5.2.10 on 2026-02-25 09:44

from django.db import migrations

import i18n_fields.md.fields


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="markdown_notes",
            field=i18n_fields.md.fields.LocalizedMartorField(
                blank=True, default=dict
            ),
        ),
    ]
